apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: grafana-agent
    releaseName: grafana-agent
    namespace: monitoring
    valuesFile: values.yaml
