apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  environment: local

resources:
  - namespace
  - grafana-agent
  - loki
  - grafana
  - tempo
  # - mimir - deactivated until confident.
  - prometheus
  - pyroscope
