# Docker-compose for unit test of Kit framework
version: '3.8'

services:

  # Kit cache dependency
  redis:
    image: redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres:14.4
    ports:
      - '5432:5432'
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgress
      - POSTGRES_USER=postgres
