apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: pyroscope
    releaseName: pyroscope
    namespace: monitoring
    valuesFile: values.yaml
