rbac:
  create: true
pyroscopeConfigs:
  log-level: debug
  scrape-configs:
    - job-name: 'kubernetes-pods'
      enabled-profiles: [cpu, mem, goroutines, mutex, block]
      kubernetes-sd-configs:
        - role: pod
      relabel-configs:
        - source-labels: [__meta_kubernetes_pod_annotation_pyroscope_io_scrape]
          action: keep
          regex: true
        - source-labels:
            [__meta_kubernetes_pod_annotation_pyroscope_io_application_name]
          action: replace
          target-label: __name__
        - source-labels:
            [__meta_kubernetes_pod_annotation_pyroscope_io_spy_name]
          action: replace
          target-label: __spy_name__
        - source-labels: [__meta_kubernetes_pod_annotation_pyroscope_io_scheme]
          action: replace
          regex: (https?)
          target-label: __scheme__
        - source-labels:
            [__address__, __meta_kubernetes_pod_annotation_pyroscope_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target-label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source-labels: [__meta_kubernetes_namespace]
          action: replace
          target-label: kubernetes_namespace
        - source-labels: [__meta_kubernetes_pod_name]
          action: replace
          target-label: kubernetes_pod_name
        - source-labels: [__meta_kubernetes_pod_phase]
          regex: Pending|Succeeded|Failed|Completed
          action: drop
        - action: labelmap
          regex: __meta_kubernetes_pod_annotation_pyroscope_io_profile_(.+)
          replacement: __profile_$1
