// Code generated by mockery v2.14.0. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Lock is an autogenerated mock type for the Lock type
type Lock struct {
	mock.Mock
}

type Lock_Expecter struct {
	mock *mock.Mock
}

func (_m *Lock) EXPECT() *Lock_Expecter {
	return &Lock_Expecter{mock: &_m.Mock}
}

// IsLock provides a mock function with given fields: ctx
func (_m *Lock) IsLock(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Lock_IsLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLock'
type Lock_IsLock_Call struct {
	*mock.Call
}

// IsLock is a helper method to define mock.On call
//  - ctx context.Context
func (_e *Lock_Expecter) IsLock(ctx interface{}) *Lock_IsLock_Call {
	return &Lock_IsLock_Call{Call: _e.mock.On("IsLock", ctx)}
}

func (_c *Lock_IsLock_Call) Run(run func(ctx context.Context)) *Lock_IsLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Lock_IsLock_Call) Return(_a0 error) *Lock_IsLock_Call {
	_c.Call.Return(_a0)
	return _c
}

// Lock provides a mock function with given fields: ctx
func (_m *Lock) Lock(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Lock_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type Lock_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//  - ctx context.Context
func (_e *Lock_Expecter) Lock(ctx interface{}) *Lock_Lock_Call {
	return &Lock_Lock_Call{Call: _e.mock.On("Lock", ctx)}
}

func (_c *Lock_Lock_Call) Run(run func(ctx context.Context)) *Lock_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Lock_Lock_Call) Return(_a0 error) *Lock_Lock_Call {
	_c.Call.Return(_a0)
	return _c
}

// Release provides a mock function with given fields:
func (_m *Lock) Release() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Lock_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type Lock_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *Lock_Expecter) Release() *Lock_Release_Call {
	return &Lock_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *Lock_Release_Call) Run(run func()) *Lock_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Lock_Release_Call) Return(_a0 error) *Lock_Release_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewLock interface {
	mock.TestingT
	Cleanup(func())
}

// NewLock creates a new instance of Lock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLock(t mockConstructorTestingTNewLock) *Lock {
	mock := &Lock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
