{{- if and .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pyroscope.clusterRoleBindingName" . }}
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pyroscope.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pyroscope.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
