---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pyroscope.fullname" . }}
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- toYaml .Values.pyroscopeConfigs | nindent 4 }}
