---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: prometheus
  app.kubernetes.io/part-of: workspace

namespace: monitoring

resources:
  - service-account.yaml
  - prometheus-config.yaml
  - deployment.yaml
